

var Product_List = [
    {
        id : 1 ,
        name: "تونیک طرح دار یقه ۷",
        tag: "مانتو" ,
        image : "static/products-image/manto-1.jpg",
        price: 2900000 ,
        off: 0 ,
        size:" دوسایز ۱ و ۲",
        color:"رنگ بندی متنوع",
    },
    {
        id : 2 ,
        name: "شومیز خامه دوزی",
        tag: "مانتو" ,
        image : "static/products-image/manto-8.jpg",
        price: 4100000 ,
        off: 0 ,
        size:"قواره بزرگ تا سایز ۵۰",
        color:"",
    },
    {
        id : 3 ,
        name: "شلوار لنین",
        tag: "شلوار" ,
        image : "static/products-image/shalvar-2.jpg",
        price: 1550000 ,
        off: 0 ,
        size:"سایز از ۳۶ تا ۴۸",
        color:"قد کار تقریبا ۱۰۰",
    },
    {
        id : 4 ,
        name: "مانتو لنین طرح دار و دکمه ای",
        tag: "مانتو" ,
        image : "static/products-image/manto-10.png",
        price: 4100000 ,
        off: 0 ,
        size:"",
        color:"رنگ بندی مختلف",
    },
    {
        id : 5 ,
        name: "مانتو خامه دوزی",
        tag: "مانتو" ,
        image : "static/products-image/manto-3.jpg",
        price: 4100000 ,
        off: 0 ,
        size:"دو سایز قواره بزرگ",
        color:"",
    },
    {
        id : 6 ,
        name: "شومیز طرح دار",
        tag: "مانتو" ,
        image : "static/products-image/manto-6.jpg",
        price: 2600000 ,
        off: 0 ,
        size:"فری سایز ",
        color:"از سایز ۳۶ تا ۴۸",
    },
    {
        id : 7 ,
        name: "شلوار پاییزی",
        tag: "شلوار" ,
        image : "static/products-image/shalvar-1.jpg",
        price: 2100000 ,
        off: 0 ,
        size:"قد کار ۹۵",
        color:"مشکی - یشمی - طوسی",
    },
    {
        id : 8 ,
        name: "تونیک زیپ دار راه راه",
        tag: "مانتو" ,
        image : "static/products-image/manto-5.jpg",
        price: 3000000 ,
        off: 2900000 ,
        size:"فری سایز",
        color:"رنگ بندی جذاب",
    },
    {
        id : 9 ,
        name: "شلوار کریشه",
        tag: "شلوار" ,
        image : "static/products-image/shalvar-5.png",
        price: 1700000 ,
        off: 1400000 ,
        size:"تا سایز ۵۰",
        color:"در رنگ های مختلف",
    },
    {
        id : 10 ,
        name: "شلوار پاییزی",
        tag: "شلوار" ,
        image : "static/products-image/shalvar-1.jpg",
        price: 2100000 ,
        off: 0 ,
        size:"قد کار ۹۵",
        color:"مشکی - یشمی - طوسی",
    },
    {
        id : 11 ,
        name: "مانتو کتی",
        tag: "مانتو" ,
        image : "static/products-image/manto-4.jpg",
        price: 3200000 ,
        off: 3050000 ,
        size:"بسیار جذاب ",
        color:"فری سایز",
    },
    {
        id : 12 ,
        name: "شلوار بگ کاغذی",
        tag: "شلوار" ,
        image : "static/products-image/shalvar-4.png",
        price: 2800000 ,
        off: 0 ,
        size:"سایز ۳۶ تا ۴۴",
        color:"در دو رنگ ",
    },
    {
        id : 13 ,
        name: "تونیک لنین جلوباز یقه ۷",
        tag: "مانتو" ,
        image : "static/products-image/manto-9.png",
        price: 3850000 ,
        off: 0 ,
        size:"فری سایز",
        color:" در 4 طرح مختلف",
    },
    
    
]


/*
    {
        id : 1 ,
        name: "Name of Product",
        tag: "شلوار" ,
        image : "../static/products-image/shalvar-1.jpg",
        price: 1100000 ,
        off: 8 ,
        size:"free size",
        color:"colors",
    },

*/
